version: '3'

services:
  mynotes-service:
    build:
      ./mynotes-springboot-service
    volumes:
      - /.h2:/.h2
    ports:
      - 8080:8080
      - 8443:8443

  mynotes-front:
    build:
      context: ./mynotes-material-client
      args:
        key_store_pass: spring
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mynotes-service
